version: "3.9"

services:
  app1:
    build: ./app_deploiment
    container_name: blockchain-app-1
    environment:
      - INSTANCE=app1
    expose:
      - "8080"

  app2:
    build: ./app_deploiment
    container_name: blockchain-app-2
    environment:
      - INSTANCE=app2
    expose:
      - "8080"

  proxy:
    build: ./reverse_proxy
    container_name: blockchain-proxy
    environment:
      - BACKENDS=http://blockchain-app-1:8080,http://blockchain-app-2:8080
    ports:
      - "8080:8443"
    depends_on:
      - app1
      - app2
